algoritmo "Calculo de Media"
// Função :  Calculo de Media
// Autor :   Marcos Vinicius Dias Oliveira
// Data : 13/08/2020
// Seção de Declarações 
var
   N1, N2, M: Real
inicio
// Seção de Comandos 
   Escreval("Feito por: Marcos Vinicius Dias Oliveira")
   Escreval("Cálculo de Média")
   Escreval
   Escreva("Informe um número: ")
   Leia(N1)
   Escreva("Informe outro número: ")
   Leia(N2)
   M <- (N1 + N2)/2
   Escreva("A média entre", N1, " e", N2, " é", M)
fimalgoritmo
