algoritmo "Raiz Quadrada"
// Função :  Calculo de Raiz Quadrada
// Autor :   Marcos Vinicius Dias Oliveira
// Data : 13/08/2020
// Seção de Declarações 
var
   N1, R: Real
inicio
// Seção de Comandos 
   Escreval("Feito por Marcos Vinicius Dias Oliveira")
   Escreval("Calculo de Raiz Quadrada")
   Escreval
   Escreva("Digite um número: ")
   Leia(N1)
   R <- RaizQ(N1)
   Escreva("A Raiz Quadrada de", N1," é", R)
fimalgoritmo
