algoritmo "Exponenciacao"
// Função :  Exponenciacao
// Autor :   Marcos Vinicius Dias Oliveira
// Data : 13/08/2020
// Seção de Declarações 
var
   N1, N2, P: Real
inicio
// Seção de Comandos 
   Escreval("Feito por Marcos Vinicius Dias Oliveira")
   Escreval("Exponeciação")
   Escreval
   Escreva("Digite a base: ")
   Leia(N1)
   Escreva("Digite o expoente: ")
   Leia(N2)
   P <- Exp(N1,N2)
   Escreva(N1, " elevado a", N2, " é igual a", P)
fimalgoritmo
